stages:
  - build
  - test

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  CUSTOM_CI_IMAGE: $CI_REGISTRY_IMAGE/ci:$CI_COMMIT_REF_SLUG
  XDG_CACHE_HOME: "$CI_PROJECT_DIR/.cache"

.nix_build_template:
  interruptible: true
  tags:
    - native-nix
  before_script:
    - git config --global --add url.${CI_SERVER_PROTOCOL}://gitlab-ci-token:${CI_JOB_TOKEN}@${CI_SERVER_HOST}/.insteadOf "git@${CI_SERVER_HOST}:"
    - git config --global --add url.${CI_SERVER_PROTOCOL}://gitlab-ci-token:${CI_JOB_TOKEN}@${CI_SERVER_HOST}/.insteadOf "ssh://git@${CI_SERVER_HOST}/"
    - unset NIX_PATH
  cache:
    key: "${CI_PROJECT_ID}-${CI_PROJECT_NAME}-nix-cache"
    paths:
      - "$CI_PROJECT_DIR/.cache/nix"

build:nixos-tests:
  stage: build
  rules:
    - when: always
  extends:
    - .nix_build_template
  dependencies: []
  script:
    - nix build -L .#tests.default.driver

test:nixos-tests:
  stage: test
  rules:
    # Resource groups do not work across forks. However, we need the resource
    # group to apply globally for the GitLab CI runner. As a workaround, we
    # only run this job in the main repository (on pull requests). Once all
    # forks were rebased, this change becomes effective.
    - if: '$CI_PROJECT_PATH == "cyberus/cloud/libvirt"'
      when: always
    - when: never
  resource_group: host-tcp-ports
  extends:
    - .nix_build_template
  dependencies: []
  variables:
    PYTHONUNBUFFERED: "1"
    TERM: "xterm"
  script:
    - nix run -L .#tests.default.driver
