workflow:
  rules:
    # For pushes, MRs, scheduled pipelines
    - when: always

stages:
  - lint
  - build
  - test

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  CUSTOM_CI_IMAGE: $CI_REGISTRY_IMAGE/ci:$CI_COMMIT_REF_SLUG
  XDG_CACHE_HOME: "$CI_PROJECT_DIR/.cache"

.nix_build_template:
  interruptible: true
  tags:
    - native-nix
  before_script:
    - git config --global --add url.${CI_SERVER_PROTOCOL}://gitlab-ci-token:${CI_JOB_TOKEN}@${CI_SERVER_HOST}/.insteadOf "git@${CI_SERVER_HOST}:"
    - git config --global --add url.${CI_SERVER_PROTOCOL}://gitlab-ci-token:${CI_JOB_TOKEN}@${CI_SERVER_HOST}/.insteadOf "ssh://git@${CI_SERVER_HOST}/"
    - unset NIX_PATH
  cache:
    key: "${CI_PROJECT_ID}-${CI_PROJECT_NAME}-nix-cache"
    paths:
      - "$CI_PROJECT_DIR/.cache/nix"

lint:commit:
  stage: lint
  rules:
      # Needed for TARGET_BRANCH below.
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: always
    - when: never
  extends:
    - .nix_build_template
  variables:
    GIT_DEPTH: "0"  # Ensures full Git history is fetched
  script:
    # Determine the target branch of the merge request
    - TARGET_BRANCH=${CI_MERGE_REQUEST_TARGET_BRANCH_NAME:-$CI_DEFAULT_BRANCH}
    - echo "TARGET_BRANCH=$TARGET_BRANCH"
    # Lint commit messages in the range from target branch to current HEAD
    - nix run nixpkgs#gitlint -- --commits origin/$TARGET_BRANCH..

lint:nix-fmt:
  stage: lint
  extends:
    - .nix_build_template
  script:
    - nix fmt -- --ci

build:packages:
  stage: build
  rules:
    - when: always
  extends:
    - .nix_build_template
  # No dependency to lint stage.
  dependencies: []
  needs: []
  script:
    - nix build -L .#libvirt
    - nix build -L .#libvirt-debugoptimized

build:nixos-tests:
  stage: build
  rules:
    - when: always
  extends:
    - .nix_build_template
  # No dependency to lint stage.
  dependencies: []
  needs: []
  script:
    - nix build -L .#tests.x86_64-linux.default.driver

test:nixos-tests:
  stage: test
  rules:
    # Resource groups do not work across forks. However, we need the resource
    # group to apply globally for the GitLab CI runner. As a workaround, we
    # only run this job in the main repository (on pull requests). Once all
    # forks were rebased, this change becomes effective.
    - if: '$CI_PROJECT_PATH == "cyberus/cloud/libvirt"'
      when: always
    - when: never
  resource_group: host-tcp-ports
  extends:
    - .nix_build_template
  variables:
    PYTHONUNBUFFERED: "1"
    TERM: "xterm"
    DBG_LOG_DIR: "./logs"
  artifacts:
    expire_in: 1 week
    when: always
    paths:
      - logs/
  script:
    # We experience CI weirdness with our runners: sometimes we see orphaned
    # QEMU processes still running and blocking host ports 2222 and 3333, thus,
    # the CI will fail.
    #
    # On the long term, we should refactor libvirt-tests to export all tests in
    # CI mode and interactive mode where only the latter also binds the host
    # ports. This here, however, is the more pragmatic workaround for now.
    - |
      echo "Checking if any orphaned QEMU process needs to be killed ..."
      
      kill_qemu() {
        local port=$1
        local pid=$(nix shell nixpkgs#procps --command bash -c "pgrep -f 'qemu.*[h]ostfwd=tcp::$port' || echo -1")
        if [ "${pid}" -gt 1 ]; then
          nix shell nixpkgs#ansi --command bash -c "echo -e \"\$(ansi red bold)FOUND ORPHANED QEMU (pid=$pid) blocking port $port: Killing to unblock pipeline\$(ansi reset)\"" 
          kill -KILL "${pid}"
        fi
      }
      
      kill_qemu 2222
      kill_qemu 3333
    - mkdir "${DBG_LOG_DIR}"
    - nix run -L .#tests.x86_64-linux.default.driver 2>&1 | tee "${DBG_LOG_DIR}/nixos_driver.log"
