workflow:
  rules:
    # For pushes, MRs, scheduled pipelines
    - when: always

stages:
  - lint
  - build
  - test

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  CUSTOM_CI_IMAGE: $CI_REGISTRY_IMAGE/ci:$CI_COMMIT_REF_SLUG
  XDG_CACHE_HOME: "$CI_PROJECT_DIR/.cache"

.nix_build_template:
  interruptible: true
  tags:
    - native-nix
  before_script:
    - git config --global --add url.${CI_SERVER_PROTOCOL}://gitlab-ci-token:${CI_JOB_TOKEN}@${CI_SERVER_HOST}/.insteadOf "git@${CI_SERVER_HOST}:"
    - git config --global --add url.${CI_SERVER_PROTOCOL}://gitlab-ci-token:${CI_JOB_TOKEN}@${CI_SERVER_HOST}/.insteadOf "ssh://git@${CI_SERVER_HOST}/"
    - unset NIX_PATH
  cache:
    key: "${CI_PROJECT_ID}-${CI_PROJECT_NAME}-nix-cache"
    paths:
      - "$CI_PROJECT_DIR/.cache/nix"

lint:commit:
  stage: lint
  rules:
      # Needed for TARGET_BRANCH below.
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: always
    - when: never
  extends:
    - .nix_build_template
  variables:
    GIT_DEPTH: "0"  # Ensures full Git history is fetched
  script:
    # Determine the target branch of the merge request
    - TARGET_BRANCH=${CI_MERGE_REQUEST_TARGET_BRANCH_NAME:-$CI_DEFAULT_BRANCH}
    - echo "TARGET_BRANCH=$TARGET_BRANCH"
    # Lint commit messages in the range from target branch to current HEAD
    - nix run nixpkgs#gitlint -- --commits origin/$TARGET_BRANCH..

lint:nix-fmt:
  stage: lint
  extends:
    - .nix_build_template
  script:
    - nix fmt -- --ci

build:packages:
  stage: build
  rules:
    - when: always
  extends:
    - .nix_build_template
  # No dependency to lint stage.
  dependencies: []
  needs: []
  script:
    - nix build -L .#libvirt
    - nix build -L .#libvirt-debugoptimized

build:nixos_tests:
  stage: build
  rules:
    - when: always
  extends:
    - .nix_build_template
  # No dependency to lint stage.
  dependencies: []
  needs: []
  script:
    - nix build -L .#tests.x86_64-linux.all_drivers

.test_nixos_tests:
  stage: test
  rules:
    # Resource groups do not work across forks. However, we need the resource
    # group to apply globally for the GitLab CI runner. As a workaround, we
    # only run this job in the main repository (on pull requests). Once all
    # forks were rebased, this change becomes effective.
    - if: '$CI_PROJECT_PATH == "cyberus/cloud/libvirt"'
      when: always
    - when: never
  extends:
    - .nix_build_template
  variables:
    PYTHONUNBUFFERED: "1"
    TERM: "xterm"
    DBG_LOG_DIR: "./logs"
  artifacts:
    expire_in: 1 week
    when: always
    paths:
      - logs/
  script:
    # Create a unique tmp directory where the nixos test driver places the VM
    # images. We must ensure to delete those directories, as they are currently
    # not automatically cleaned up after the CI run finishes.
    - TMPDIR=$(mktemp -d)
    - export TMPDIR
    - trap 'rm -rf "$TMPDIR"' EXIT
    - mkdir "${DBG_LOG_DIR}"
    - nix run -L .#tests.x86_64-linux.$TEST_ATTR.passthru.no_port_forwarding.driver 2>&1 | tee "${DBG_LOG_DIR}/nixos_driver.log"

test:default-tests:
  extends:
    - .test_nixos_tests
  variables:
    TEST_ATTR: default

test:live-migration-tests:
  extends:
    - .test_nixos_tests
  variables:
    TEST_ATTR: live_migration

test:hugepage-tests:
  extends:
    - .test_nixos_tests
  variables:
    TEST_ATTR: hugepage
